### ISSUE TITLE
ERROR in ./node_modules/selenium-webdriver/http/index.js Module not found: Error: Can't resolve 'http' in '/node_modules/selenium-webdriver/http'

### ISSUE THREAD

**Issue by karanShinde7** [serenity-js/seed-cucumber#3]
'use strict';
const http = require('http');
const https = require('https');
const url = require('url');
const httpLib = require('../lib/http');
-- this is code from selenium-webdriver/http/index.js--
 *****
ERROR in ./node_modules/selenium-webdriver/http/index.js
Module not found: Error: Can't resolve 'http' in '/Users/mac/angular/restaurantApp/node_modules/selenium-webdriver/http'
ERROR in ./node_modules/selenium-webdriver/http/index.js
Module not found: Error: Can't resolve 'https' in '/Users/mac/angular/restaurantApp/node_modules/selenium-webdriver/http'
--these are the errors--
*****
package.json
{
  "name": "restaurant-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.7",
    "@angular/cdk": "^6.3.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/flex-layout": "^6.0.0-beta.15",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.3.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@auth0/angular-jwt": "^2.0.0",
    "angular-material-icons": "^0.7.1",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}

**Comment by jan-molak** [comment]
Hi @karanShinde7 and thanks for submitting this ticket. Could you please give me a bit more context?
What are you trying to do? What is the behaviour you're expecting and what are you seeing instead?

Thanks,
Jan

**Comment by prodigits** [comment]
I found out it was importing the HttpClient class from selenium instead of angular/common/http

more detailed answer here

https://stackoverflow.com/questions/51287558/module-not-found-error-cant-resolve-http-in-selenium-webdriver
