### ISSUE TITLE
All tests going to pending status and single scenario is not working  

### ISSUE THREAD

**Issue by siva90144** [serenity-js/seed-cucumber#4]
1. After executing npm test all tests going to pending status
2. Adding tag as @wip1 and i tried to run npm run scenario "@wip1". its not executing.
3. I have commented below code in config file. its not opening the browser even though headless option is disabled. 
                 // '--disable-infobars',
                // '--headless',
                // '--disable-gpu',
                // '--window-size=800,600'

**Comment by jan-molak** [comment]
The `seed-cucumber` project was developed for Serenity/JS v1 and is no longer maintained. Please have a look at the [Protractor/Cucumber template for Serenity/JS v2](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) and let me know what you think!
